# Generated by Django 6.0.3 on 2026-06-05 05:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocusSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MLVAUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mlva_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('settings', models.JSONField(default=dict, help_text='User preferences and settings stored as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'MLVA Users',
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Investigations',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='Isolate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sampling_date', models.DateField()),
                ('sampling_location', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assembly_size', models.BigIntegerField(default=0)),
                ('contig_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Whether this isolate is included in analyses and visualizations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('n50', models.IntegerField(blank=True, default=0, help_text='N50 value calculated from contig lengths', null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolates', to='core.investigation')),
            ],
            options={
                'verbose_name_plural': 'Isolates',
                'ordering': ['-sampling_date'],
            },
        ),
        migrations.CreateModel(
            name='Contig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasta_header', models.CharField(max_length=500)),
                ('sequence', models.TextField()),
                ('length', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('gc_content', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isolate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contigs', to='core.isolate')),
            ],
            options={
                'ordering': ['isolate', 'fasta_header'],
            },
        ),
        migrations.CreateModel(
            name='Locus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('forward_primer', models.CharField(help_text="5' to 3' forward primer sequence", max_length=500)),
                ('reverse_primer', models.CharField(help_text="5' to 3' reverse primer sequence", max_length=500)),
                ('repeat_sequence', models.CharField(help_text='Tandem repeat sequence to count', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locus_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loci', to='core.locusset')),
            ],
            options={
                'verbose_name_plural': 'Loci',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MLVAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_mode', models.CharField(choices=[('uncounted', 'Uncounted'), ('counted', 'Counted')], default='uncounted', help_text='How to count repeats in tandem repeat regions', max_length=20)),
                ('jobs', models.JSONField(default=dict, help_text='Dictionary mapping job IDs to job metadata (status, timestamps, etc)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlva_configs', to='core.investigation')),
                ('locus_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locusset')),
            ],
            options={
                'verbose_name': 'MLVA Configuration',
                'verbose_name_plural': 'MLVA Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocusResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_count', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locus_results', to='core.contig')),
                ('locus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.locus')),
                ('mlva_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locus_results', to='core.mlvaconfig')),
            ],
            options={
                'verbose_name_plural': 'Locus Results',
                'ordering': ['contig', 'locus'],
            },
        ),
        migrations.CreateModel(
            name='UserInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='core.investigation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='isolate',
            index=models.Index(fields=['investigation', 'active'], name='core_isolat_investi_bb13a1_idx'),
        ),
        migrations.AddIndex(
            model_name='isolate',
            index=models.Index(fields=['sampling_date'], name='core_isolat_samplin_ccce22_idx'),
        ),
        migrations.AddConstraint(
            model_name='isolate',
            constraint=models.UniqueConstraint(fields=('investigation', 'name'), name='unique_isolate_name_per_investigation'),
        ),
        migrations.AlterUniqueTogether(
            name='locus',
            unique_together={('locus_set', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='mlvaconfig',
            unique_together={('investigation', 'locus_set', 'count_mode')},
        ),
        migrations.AddIndex(
            model_name='locusresult',
            index=models.Index(fields=['mlva_config', 'contig'], name='core_locusr_mlva_co_c89a22_idx'),
        ),
        migrations.AddIndex(
            model_name='locusresult',
            index=models.Index(fields=['contig', 'locus'], name='core_locusr_contig__3ea7c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='locusresult',
            unique_together={('mlva_config', 'contig', 'locus')},
        ),
        migrations.AlterUniqueTogether(
            name='userinvestigation',
            unique_together={('user', 'investigation')},
        ),
    ]
