"""Regression tests for MLVA and STRD calculation scripts.

This module tests the mlva.py and calc_strd.py scripts against fixture data
to ensure the output remains consistent with legacy results. Tests verify that:
- MLVA profiles are correctly generated from assembly files
- STRD matrices are correctly computed from MLVA profiles
- Both counted and uncounted modes produce expected results
"""
from __future__ import annotations

import csv
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT_DIR = Path(__file__).resolve().parents[1]
CALC_DIR = ROOT_DIR / "core" / "utils" / "calculations"
LEGACY_RESULTS_DIR = ROOT_DIR / "tests" / "fixtures"
ASSEMBLIES_DIR = CALC_DIR / "assemblies"
MLVA_SCRIPT = CALC_DIR / "mlva.py"
STRD_SCRIPT = CALC_DIR / "calc_strd.py"
PRIMER_FASTA = CALC_DIR / "cd_primers.fasta"


@pytest.fixture(scope="session")
def assembly_files() -> list[Path]:
    """Load all assembly files from the assemblies directory.
    
    Returns:
        Sorted list of paths to .fna assembly files.
    """
    return sorted(ASSEMBLIES_DIR.glob("*.fna"))


def _run_script(script: Path, args: list[str]) -> None:
    """Execute a Python script with given arguments.
    
    Args:
        script: Path to the Python script to execute.
        args: List of command-line arguments to pass to the script.
        
    Raises:
        AssertionError: If the script exits with non-zero status.
    """
    process = subprocess.run(
        [sys.executable, str(script), *args],
        capture_output=True,
        text=True,
        cwd=ROOT_DIR,
    )
    assert process.returncode == 0, (
        f"Command failed: {script.name}\n"
        f"STDOUT:\n{process.stdout}\n"
        f"STDERR:\n{process.stderr}"
    )


def _read_csv(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    """Read a CSV file and return headers and rows.
    
    Args:
        path: Path to the CSV file to read.
        
    Returns:
        Tuple of (header_list, row_list) where each row is a dict.
    """
    with path.open("r", newline="") as handle:
        reader = csv.DictReader(handle)
        return list(reader.fieldnames or []), list(reader)


def _assert_csv_matches(actual: Path, expected: Path) -> None:
    """Assert that two CSV files have identical headers and rows.
    
    Args:
        actual: Path to the actual CSV file generated by a test.
        expected: Path to the expected/fixture CSV file.
        
    Raises:
        AssertionError: If headers or rows don't match.
    """
    actual_headers, actual_rows = _read_csv(actual)
    expected_headers, expected_rows = _read_csv(expected)
    assert actual_headers == expected_headers
    assert actual_rows == expected_rows


@pytest.mark.parametrize(
    ("count_mode", "fixture_name"),
    [
        (False, "mlva_profiles.csv"),
        (True, "mlva_profiles_counted.csv"),
    ],
)
def test_mlva_profiles_match_legacy_fixtures(
    tmp_path: Path,
    assembly_files: list[Path],
    count_mode: bool,
    fixture_name: str,
) -> None:
    """Test that mlva.py generates MLVA profiles matching legacy fixtures.
    
    Tests both counted and uncounted modes:
    - Without -c flag: generates mlva_profiles.csv
    - With -c flag: generates mlva_profiles_counted.csv
    
    Args:
        tmp_path: Temporary directory for test output.
        assembly_files: List of assembly file paths.
        count_mode: Whether to run mlva.py in count mode (-c flag).
        fixture_name: Expected fixture filename.
        
    Note:
        Requires blastn to be installed. Test is skipped if blastn is unavailable.
    """
    if shutil.which("blastn") is None:
        pytest.skip("blastn is required to run mlva.py regression tests")

    output_csv = tmp_path / fixture_name
    args = [
        "-f",
        *(str(path) for path in assembly_files),
        "-v",
        str(PRIMER_FASTA),
        "-o",
        str(output_csv),
    ]
    if count_mode:
        args.append("-c")

    _run_script(MLVA_SCRIPT, args)
    _assert_csv_matches(output_csv, LEGACY_RESULTS_DIR / fixture_name)


@pytest.mark.parametrize(
    ("input_fixture", "expected_fixture"),
    [
        ("mlva_profiles.csv", "strd_matrix.csv"),
        ("mlva_profiles_counted.csv", "strd_matrix_counted.csv"),
    ],
)
def test_strd_matrix_matches_legacy_fixtures(
    tmp_path: Path,
    input_fixture: str,
    expected_fixture: str,
) -> None:
    """Test that calc_strd.py generates STRD matrices matching legacy fixtures.
    
    Tests both regular and counted MLVA profiles as input:
    - mlva_profiles.csv → strd_matrix.csv
    - mlva_profiles_counted.csv → strd_matrix_counted.csv
    
    The test uses legacy MLVA profile fixtures as input and compares the
    generated STRD matrix against the expected legacy fixture, skipping CDR6 locus.
    
    Args:
        tmp_path: Temporary directory for test output.
        input_fixture: Name of input MLVA profiles fixture.
        expected_fixture: Name of expected STRD matrix fixture.
    """
    output_csv = tmp_path / expected_fixture

    _run_script(
        STRD_SCRIPT,
        [
            str(LEGACY_RESULTS_DIR / input_fixture),
            "-o",
            str(output_csv),
            "--skip_loci",
            "CDR6",
        ],
    )

    _assert_csv_matches(output_csv, LEGACY_RESULTS_DIR / expected_fixture)
